// This file is auto-generated by @hey-api/openapi-ts

export type Account = {
  created_at: string;
  id: number;
  updated_at: string | null;
  user_id: string;
};

export type CreateProjectParams = {
  /**
   * A URL to the JSON Schema for this object.
   */
  readonly $schema?: string;
  name: string;
};

export type ErrorDetail = {
  /**
   * Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id'
   */
  location?: string;
  /**
   * Error message text
   */
  message?: string;
  /**
   * The value at the given location
   */
  value?: unknown;
};

export type ErrorModel = {
  /**
   * A URL to the JSON Schema for this object.
   */
  readonly $schema?: string;
  /**
   * A human-readable explanation specific to this occurrence of the problem.
   */
  detail?: string;
  /**
   * Optional list of individual error details
   */
  errors?: Array<ErrorDetail> | null;
  /**
   * A URI reference that identifies the specific occurrence of the problem.
   */
  instance?: string;
  /**
   * HTTP status code
   */
  status?: number;
  /**
   * A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
   */
  title?: string;
  /**
   * A URI reference to human-readable documentation for the error.
   */
  type?: string;
};

export type HealthCheckOutputBody = {
  /**
   * A URL to the JSON Schema for this object.
   */
  readonly $schema?: string;
  message: string;
};

export type Project = {
  /**
   * A URL to the JSON Schema for this object.
   */
  readonly $schema?: string;
  created_at: string;
  id: number;
  name: string;
  owner_id: number;
  updated_at: string | null;
};

export type SingleAccountResponseBody = {
  /**
   * A URL to the JSON Schema for this object.
   */
  readonly $schema?: string;
  account: Account;
};

export type UpdateProjectParams = {
  /**
   * A URL to the JSON Schema for this object.
   */
  readonly $schema?: string;
  name: string;
};

export type DeleteAccountData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/accounts";
};

export type DeleteAccountErrors = {
  /**
   * Error
   */
  default: ErrorModel;
};

export type DeleteAccountError = DeleteAccountErrors[keyof DeleteAccountErrors];

export type DeleteAccountResponses = {
  /**
   * No Content
   */
  204: void;
};

export type DeleteAccountResponse =
  DeleteAccountResponses[keyof DeleteAccountResponses];

export type GetAccountData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/accounts";
};

export type GetAccountErrors = {
  /**
   * Error
   */
  default: ErrorModel;
};

export type GetAccountError = GetAccountErrors[keyof GetAccountErrors];

export type GetAccountResponses = {
  /**
   * OK
   */
  200: SingleAccountResponseBody;
};

export type GetAccountResponse = GetAccountResponses[keyof GetAccountResponses];

export type CreateAccountData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/accounts";
};

export type CreateAccountErrors = {
  /**
   * Error
   */
  default: ErrorModel;
};

export type CreateAccountError = CreateAccountErrors[keyof CreateAccountErrors];

export type CreateAccountResponses = {
  /**
   * Created
   */
  201: SingleAccountResponseBody;
};

export type CreateAccountResponse =
  CreateAccountResponses[keyof CreateAccountResponses];

export type HealthCheckData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/health";
};

export type HealthCheckErrors = {
  /**
   * Error
   */
  default: ErrorModel;
};

export type HealthCheckError = HealthCheckErrors[keyof HealthCheckErrors];

export type HealthCheckResponses = {
  /**
   * OK
   */
  200: HealthCheckOutputBody;
};

export type HealthCheckResponse =
  HealthCheckResponses[keyof HealthCheckResponses];

export type CreateProjectData = {
  body: CreateProjectParams;
  path?: never;
  query?: never;
  url: "/project";
};

export type CreateProjectErrors = {
  /**
   * Error
   */
  default: ErrorModel;
};

export type CreateProjectError = CreateProjectErrors[keyof CreateProjectErrors];

export type CreateProjectResponses = {
  /**
   * Created
   */
  201: Project;
};

export type CreateProjectResponse =
  CreateProjectResponses[keyof CreateProjectResponses];

export type GetAccountProjectsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/projects";
};

export type GetAccountProjectsErrors = {
  /**
   * Error
   */
  default: ErrorModel;
};

export type GetAccountProjectsError =
  GetAccountProjectsErrors[keyof GetAccountProjectsErrors];

export type GetAccountProjectsResponses = {
  /**
   * OK
   */
  200: Array<Project> | null;
};

export type GetAccountProjectsResponse =
  GetAccountProjectsResponses[keyof GetAccountProjectsResponses];

export type DeleteProjectData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: "/projects/{id}";
};

export type DeleteProjectErrors = {
  /**
   * Error
   */
  default: ErrorModel;
};

export type DeleteProjectError = DeleteProjectErrors[keyof DeleteProjectErrors];

export type DeleteProjectResponses = {
  /**
   * No Content
   */
  204: void;
};

export type DeleteProjectResponse =
  DeleteProjectResponses[keyof DeleteProjectResponses];

export type GetProjectByIdData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: "/projects/{id}";
};

export type GetProjectByIdErrors = {
  /**
   * Error
   */
  default: ErrorModel;
};

export type GetProjectByIdError =
  GetProjectByIdErrors[keyof GetProjectByIdErrors];

export type GetProjectByIdResponses = {
  /**
   * OK
   */
  200: Project;
};

export type GetProjectByIdResponse =
  GetProjectByIdResponses[keyof GetProjectByIdResponses];

export type UpdateProjectData = {
  body: UpdateProjectParams;
  path: {
    id: number;
  };
  query?: never;
  url: "/projects/{id}";
};

export type UpdateProjectErrors = {
  /**
   * Error
   */
  default: ErrorModel;
};

export type UpdateProjectError = UpdateProjectErrors[keyof UpdateProjectErrors];

export type UpdateProjectResponses = {
  /**
   * No Content
   */
  204: void;
};

export type UpdateProjectResponse =
  UpdateProjectResponses[keyof UpdateProjectResponses];
